services:
  parser: 
    build: 
      ./parser
    depends_on:
      - bd

  backend:
    build: 
      ./backend
    ports:
      - ""
    depends_on:
      - bd
  
  bd:
    build:
      ./bd
    ports:
      - ""